# Usa una imagen base con Node.js
FROM node:20 AS development

WORKDIR /app

# Copia los archivos de dependencias
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el código fuente del proyecto
COPY . .

# Exponer el puerto 5173
EXPOSE 5173

# Ejecuta el servidor de desarrollo
CMD ["npm", "run", "dev", "--", "--host"]